### ISSUE TITLE
1px gap above navbar on large screens

### ISSUE THREAD

**Issue by oraimond** [onwidget/astrowind#412] opened 2024-04-05 16:08 UTC
On large screen formats (I believe 1536px and up) there seems to be a small 1px gap between the navbar and the top of the page. When I edit the CSS to have `top: -1px` rather than `top: 0` this fixes the issue, but it only seems to be present on large screens:
![image](https://github.com/onwidget/astrowind/assets/72635595/6f8c9898-f458-4043-994f-97b5e95c34b7)

**Comment by oraimond** [comment] 2024-04-05 16:14
My band-aid solution was to just add `2xl:top-[-1px]` to the header class list.

**Comment by prototypa** [comment] 2024-04-07 02:04
Hi @oraimond 

We had not noticed this. It is true that it is happening for large devices. If you want you can make a PR yourself with the adjustment.

**Comment by StefanMarAntonsson** [comment] 2024-04-09 00:00
This seems to be a Chromium issue (I could not replicate it in Firefox) and I traced it back to the font size for some reason. The font size for the HTML element is set to 20px and if I change it to 19px or 21px, it seems to resolve the issue and the gap goes away. ```@media (min-width: 1536px).\32xl\:text-\[20px\] { font-size: 20px; }``` is the CSS code that is what is seemingly the cause here and I assume this is a Tailwind thing but I'm not an expert on Tailwind so I can't say for sure. My fix was simple to change the font size.

**Comment by prototypa** [comment] 2024-04-11 00:49
Closed, resolved by @StefanMarAntonsson with https://github.com/onwidget/astrowind/pull/416.

Thanks @oraimond and @StefanMarAntonsson.

**Closed by prototypa** 2024-04-11 00:49 UTC
